version: "3.3"
services:
  dashboard:
    build: .
    image: maxjf1/easytopic-dashboard-api:latest
    command: npm run dev
    volumes:
      - ./:/app
    depends_on:
      - rabbitmq
    ports:
      - 8080:3000
    environment:
      QUEUE_SERVER: "rabbitmq:5672"
      OCR_INPUT_QUEUE: "ocr-in"
      OCR_OUTPUT_QUEUE: "ocr-out"
      FILES_SERVER: "files:3001"
  files:
    build: https://github.com/easytopic-project/node-files-microservice.git
    image: maxjf1/node-files-microservice:latest
    ports:
      - 3001:3001
    volumes:
      - ./temp/files:/files
    environment:
      PORT: 3001

  ocr:
    build: https://github.com/maxjf1/node-ocr-server.git
    image: maxjf1/node-ocr-server:latest
    depends_on:
      - rabbitmq
    volumes:
      - ./temp/ocr:/temp
    environment:
      QUEUE_SERVER: "rabbitmq:5672"
      FILES_SERVER: "files:3001"
      INPUT_QUEUE_NAME: "ocr-in"
      OUTPUT_QUEUE_NAME: "ocr-out"
  ocr-test:
    build: https://github.com/maxjf1/node-ocr-server.git
    image: maxjf1/node-ocr-server:latest
    depends_on:
      - rabbitmq
    volumes:
      - ./temp/ocr-test:/temp
    environment:
      QUEUE_SERVER: "rabbitmq:5672"
      FILES_SERVER: "files:3001"
      INPUT_QUEUE_NAME: "ocr-in-test"
      OUTPUT_QUEUE_NAME: "ocr-out-test"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - ./temp/rabbitmq:/var/lib/rabbitmq/mnesia/
